theme: jekyll-theme-cayman
title: Daphne Liu
description: Android developer, hackathon winner, speaker and writer. Mentored by Google and worked at 3 internships. @ GHC 2019 | Seeking for January or May 2020 internships.
